spring:
  application:
    name: tally

  datasource:
    url: jdbc:h2:file:./finance-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update        # creates/updates schema automatically on startup
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TALLY_OIDC_ISSUER:http://localhost:8180/realms/tally}
          jwk-set-uri: ${TALLY_OIDC_JWKS:http://localhost:8180/realms/tally/protocol/openid-connect/certs}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    oauth:
      client-id: tally
      use-pkce-with-authorization-code-grant: true

# App flags
app:
  ui:
    enabled: true
  oauth:
    authorization-uri: ${TALLY_OIDC_AUTH:http://localhost:8180/realms/tally/protocol/openid-connect/auth}
    token-uri: ${TALLY_OIDC_TOKEN:http://localhost:8180/realms/tally/protocol/openid-connect/token}
