package com.finance.manager.repository;

import com.finance.manager.Expense;
import com.finance.manager.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

/** User-scoped expense queries generated by Spring Data and Hibernate. */
public interface ExpenseRepository extends JpaRepository<Expense, Long> {
    List<Expense> findAllByOwnerOrderByDateDescIdDesc(User owner);
    Optional<Expense> findByIdAndOwner(Long id, User owner);
    List<Expense> findByOwnerAndCategoryIgnoreCase(User owner, String category);
    void deleteAllByOwner(User owner);
    List<Expense> findAllByOwnerIsNull();

    @Query("select coalesce(sum(e.amount), 0) from Expense e where e.owner = :owner")
    BigDecimal sumAmountsByOwner(User owner);
}
